### ISSUE TITLE
Fill color not applying

### ISSUE THREAD

**Issue by attheodo** [mkolsv/circle-progress.vue#10]
I am using the component as such:
```
   <circular-progress-bar :value="{{ business.average_communication_rating|stringformat:"0.2f" }}" :max="5" size="40" stroke-Width="12" colorFilled="#fd5b50"  rounded>
  <span class="text-xs font-extrabold">{{ business.average_communication_rating|stringformat:"0.1f" }}</span>
  </circular-progress-bar>
 ```
 
 However I don't see the fill color applying properly. I am loading the latest version of the library through unpkg

**Comment by attheodo** [comment]
Adding console log error for reference:

<img width="970" alt="image" src="https://github.com/user-attachments/assets/d1440269-65b4-4768-b180-5754d3cf9292">

Looks like `colorFilled` is being ignored but if passed like `:colorFilled` it creates an error.
Sorry, I am not really seasoned on Vue.

**Comment by mkolsv** [comment]
@attheodo Hey. Are you sure that you're using this library?

The usage of this component is slightly different from what you shared.

You are trying to use:
`<circular-progress-bar.....>...</circular-progress-bar>
`

The name of this component is different:
`<CircleProgressBar....>...</CircleProgressBar>`

**Comment by attheodo** [comment]
Yes this is the one that I am using. I am loading the script from CDN vs from import and I had some trouble registering the component as CircleProgressBar. Looks like `circular-progress-bar` is working tho. Still have issues with filling color. It could be that I am doing something entirely wrong, sorry not really well versed in JS. Can you show me what would be the proper way of loading the component as an external script (i.e from unpkg.com)?

**Comment by attheodo** [comment]
Turns out it was PEBKAC. I was using `colorFilled` vs `color-filled`. Sorry about that!
