### ISSUE TITLE
Circle cut off outside

### ISSUE THREAD

**Issue by battlezoneyt** [mkolsv/circle-progress.vue#5]
<CircleProgressBar :value="1" :max="10" size='200px' strokeWidth='25px' rounded/>

if we use strokeWidth higher than 10px it is looking like in picture attached i am using v^3.2.0

![Screenshot 2024-04-13 173825](https://github.com/mkolsv/circle-progress.vue/assets/65971185/455d82da-3fd2-420a-909e-d9800d12efd3)

**Comment by mkolsv** [comment]
Hi @battlezoneyt 

Thank you for reporting. I just released a new package version (3.2.1) where I fixed this issue. Could you please check it out?
