### ISSUE TITLE
Start on top

### ISSUE THREAD

**Issue by Milchreis** [mkolsv/circle-progress.vue#8]
Hello Misha,

I really like this component. It's small, easy to use and just works. Thank you for that 😊.
In my case I am using it for a timer and there I would assume that the circle starts at the top (12 o'clock) and goes around. Do you think it is possible to add this behavior?

Regards
Nick

**Comment by mkolsv** [comment]
Hi @Milchreis 
Sure, I will try to add that behaviour this week. 

Thank you for using this component.

**Comment by mkolsv** [comment]
Hi @Milchreis 

I added a new prop `startAngle` in the latest version (`v3.3.0`)

Now you can specify the starting point of the filling circle.

The default is - 180.

To start filling the circle from the top you can set startAngle to 0:

```
<CircleProgressBar
  ...some props
  :start-angle="0"
/>
```

**Comment by Milchreis** [comment]
It works perfect. Thank you very much for this feature 😊👍
